// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: temporal/api/enums/v1/batch_operation.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Temporalio.Api.Enums.V1 {

  /// <summary>Holder for reflection information generated from temporal/api/enums/v1/batch_operation.proto</summary>
  public static partial class BatchOperationReflection {

    #region Descriptor
    /// <summary>File descriptor for temporal/api/enums/v1/batch_operation.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static BatchOperationReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cit0ZW1wb3JhbC9hcGkvZW51bXMvdjEvYmF0Y2hfb3BlcmF0aW9uLnByb3Rv",
            "EhV0ZW1wb3JhbC5hcGkuZW51bXMudjEq4QEKEkJhdGNoT3BlcmF0aW9uVHlw",
            "ZRIkCiBCQVRDSF9PUEVSQVRJT05fVFlQRV9VTlNQRUNJRklFRBAAEiIKHkJB",
            "VENIX09QRVJBVElPTl9UWVBFX1RFUk1JTkFURRABEh8KG0JBVENIX09QRVJB",
            "VElPTl9UWVBFX0NBTkNFTBACEh8KG0JBVENIX09QRVJBVElPTl9UWVBFX1NJ",
            "R05BTBADEh8KG0JBVENIX09QRVJBVElPTl9UWVBFX0RFTEVURRAEEh4KGkJB",
            "VENIX09QRVJBVElPTl9UWVBFX1JFU0VUEAUqpgEKE0JhdGNoT3BlcmF0aW9u",
            "U3RhdGUSJQohQkFUQ0hfT1BFUkFUSU9OX1NUQVRFX1VOU1BFQ0lGSUVEEAAS",
            "IQodQkFUQ0hfT1BFUkFUSU9OX1NUQVRFX1JVTk5JTkcQARIjCh9CQVRDSF9P",
            "UEVSQVRJT05fU1RBVEVfQ09NUExFVEVEEAISIAocQkFUQ0hfT1BFUkFUSU9O",
            "X1NUQVRFX0ZBSUxFRBADQosBChhpby50ZW1wb3JhbC5hcGkuZW51bXMudjFC",
            "E0JhdGNoT3BlcmF0aW9uUHJvdG9QAVohZ28udGVtcG9yYWwuaW8vYXBpL2Vu",
            "dW1zL3YxO2VudW1zqgIXVGVtcG9yYWxpby5BcGkuRW51bXMuVjHqAhpUZW1w",
            "b3JhbGlvOjpBcGk6OkVudW1zOjpWMWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Temporalio.Api.Enums.V1.BatchOperationType), typeof(global::Temporalio.Api.Enums.V1.BatchOperationState), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum BatchOperationType {
    [pbr::OriginalName("BATCH_OPERATION_TYPE_UNSPECIFIED")] Unspecified = 0,
    [pbr::OriginalName("BATCH_OPERATION_TYPE_TERMINATE")] Terminate = 1,
    [pbr::OriginalName("BATCH_OPERATION_TYPE_CANCEL")] Cancel = 2,
    [pbr::OriginalName("BATCH_OPERATION_TYPE_SIGNAL")] Signal = 3,
    [pbr::OriginalName("BATCH_OPERATION_TYPE_DELETE")] Delete = 4,
    [pbr::OriginalName("BATCH_OPERATION_TYPE_RESET")] Reset = 5,
  }

  public enum BatchOperationState {
    [pbr::OriginalName("BATCH_OPERATION_STATE_UNSPECIFIED")] Unspecified = 0,
    [pbr::OriginalName("BATCH_OPERATION_STATE_RUNNING")] Running = 1,
    [pbr::OriginalName("BATCH_OPERATION_STATE_COMPLETED")] Completed = 2,
    [pbr::OriginalName("BATCH_OPERATION_STATE_FAILED")] Failed = 3,
  }

  #endregion

}

#endregion Designer generated code
