// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: temporal/api/enums/v1/reset.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Temporalio.Api.Enums.V1 {

  /// <summary>Holder for reflection information generated from temporal/api/enums/v1/reset.proto</summary>
  public static partial class ResetReflection {

    #region Descriptor
    /// <summary>File descriptor for temporal/api/enums/v1/reset.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ResetReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiF0ZW1wb3JhbC9hcGkvZW51bXMvdjEvcmVzZXQucHJvdG8SFXRlbXBvcmFs",
            "LmFwaS5lbnVtcy52MSrsAQoXUmVzZXRSZWFwcGx5RXhjbHVkZVR5cGUSKgom",
            "UkVTRVRfUkVBUFBMWV9FWENMVURFX1RZUEVfVU5TUEVDSUZJRUQQABIlCiFS",
            "RVNFVF9SRUFQUExZX0VYQ0xVREVfVFlQRV9TSUdOQUwQARIlCiFSRVNFVF9S",
            "RUFQUExZX0VYQ0xVREVfVFlQRV9VUERBVEUQAhIkCiBSRVNFVF9SRUFQUExZ",
            "X0VYQ0xVREVfVFlQRV9ORVhVUxADEjEKKVJFU0VUX1JFQVBQTFlfRVhDTFVE",
            "RV9UWVBFX0NBTkNFTF9SRVFVRVNUEAQaAggBKpcBChBSZXNldFJlYXBwbHlU",
            "eXBlEiIKHlJFU0VUX1JFQVBQTFlfVFlQRV9VTlNQRUNJRklFRBAAEh0KGVJF",
            "U0VUX1JFQVBQTFlfVFlQRV9TSUdOQUwQARIbChdSRVNFVF9SRUFQUExZX1RZ",
            "UEVfTk9ORRACEiMKH1JFU0VUX1JFQVBQTFlfVFlQRV9BTExfRUxJR0lCTEUQ",
            "AypuCglSZXNldFR5cGUSGgoWUkVTRVRfVFlQRV9VTlNQRUNJRklFRBAAEiIK",
            "HlJFU0VUX1RZUEVfRklSU1RfV09SS0ZMT1dfVEFTSxABEiEKHVJFU0VUX1RZ",
            "UEVfTEFTVF9XT1JLRkxPV19UQVNLEAJCggEKGGlvLnRlbXBvcmFsLmFwaS5l",
            "bnVtcy52MUIKUmVzZXRQcm90b1ABWiFnby50ZW1wb3JhbC5pby9hcGkvZW51",
            "bXMvdjE7ZW51bXOqAhdUZW1wb3JhbGlvLkFwaS5FbnVtcy5WMeoCGlRlbXBv",
            "cmFsaW86OkFwaTo6RW51bXM6OlYxYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Temporalio.Api.Enums.V1.ResetReapplyExcludeType), typeof(global::Temporalio.Api.Enums.V1.ResetReapplyType), typeof(global::Temporalio.Api.Enums.V1.ResetType), }, null, null));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// Event types to exclude when reapplying events beyond the reset point.
  /// </summary>
  public enum ResetReapplyExcludeType {
    [pbr::OriginalName("RESET_REAPPLY_EXCLUDE_TYPE_UNSPECIFIED")] Unspecified = 0,
    /// <summary>
    /// Exclude signals when reapplying events beyond the reset point.
    /// </summary>
    [pbr::OriginalName("RESET_REAPPLY_EXCLUDE_TYPE_SIGNAL")] Signal = 1,
    /// <summary>
    /// Exclude updates when reapplying events beyond the reset point.
    /// </summary>
    [pbr::OriginalName("RESET_REAPPLY_EXCLUDE_TYPE_UPDATE")] Update = 2,
    /// <summary>
    /// Exclude nexus events when reapplying events beyond the reset point.
    /// </summary>
    [pbr::OriginalName("RESET_REAPPLY_EXCLUDE_TYPE_NEXUS")] Nexus = 3,
    /// <summary>
    /// Deprecated, unimplemented option.
    /// </summary>
    [global::System.ObsoleteAttribute]
    [pbr::OriginalName("RESET_REAPPLY_EXCLUDE_TYPE_CANCEL_REQUEST")] CancelRequest = 4,
  }

  /// <summary>
  /// Event types to include when reapplying events. Deprecated: applications
  /// should use ResetReapplyExcludeType to specify exclusions from this set, and
  /// new event types should be added to ResetReapplyExcludeType instead of here.
  /// </summary>
  public enum ResetReapplyType {
    [pbr::OriginalName("RESET_REAPPLY_TYPE_UNSPECIFIED")] Unspecified = 0,
    /// <summary>
    /// Signals are reapplied when workflow is reset.
    /// </summary>
    [pbr::OriginalName("RESET_REAPPLY_TYPE_SIGNAL")] Signal = 1,
    /// <summary>
    /// No events are reapplied when workflow is reset.
    /// </summary>
    [pbr::OriginalName("RESET_REAPPLY_TYPE_NONE")] None = 2,
    /// <summary>
    /// All eligible events are reapplied when workflow is reset.
    /// </summary>
    [pbr::OriginalName("RESET_REAPPLY_TYPE_ALL_ELIGIBLE")] AllEligible = 3,
  }

  /// <summary>
  /// Reset type options. Deprecated, see temporal.api.common.v1.ResetOptions.
  /// </summary>
  public enum ResetType {
    [pbr::OriginalName("RESET_TYPE_UNSPECIFIED")] Unspecified = 0,
    /// <summary>
    /// Resets to event of the first workflow task completed, or if it does not exist, the event after task scheduled.
    /// </summary>
    [pbr::OriginalName("RESET_TYPE_FIRST_WORKFLOW_TASK")] FirstWorkflowTask = 1,
    /// <summary>
    /// Resets to event of the last workflow task completed, or if it does not exist, the event after task scheduled.
    /// </summary>
    [pbr::OriginalName("RESET_TYPE_LAST_WORKFLOW_TASK")] LastWorkflowTask = 2,
  }

  #endregion

}

#endregion Designer generated code
