// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: temporal/api/enums/v1/time_skipping.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Temporalio.Api.Enums.V1 {

  /// <summary>Holder for reflection information generated from temporal/api/enums/v1/time_skipping.proto</summary>
  public static partial class TimeSkippingReflection {

    #region Descriptor
    /// <summary>File descriptor for temporal/api/enums/v1/time_skipping.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TimeSkippingReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cil0ZW1wb3JhbC9hcGkvZW51bXMvdjEvdGltZV9za2lwcGluZy5wcm90bxIV",
            "dGVtcG9yYWwuYXBpLmVudW1zLnYxKuIBChhGYXN0Rm9yd2FyZFBvbGxpbmdS",
            "ZXN1bHQSKwonRkFTVF9GT1JXQVJEX1BPTExJTkdfUkVTVUxUX1VOU1BFQ0lG",
            "SUVEEAASLAooRkFTVF9GT1JXQVJEX1BPTExJTkdfUkVTVUxUX1BPTExfVElN",
            "RU9VVBABEjYKMkZBU1RfRk9SV0FSRF9QT0xMSU5HX1JFU1VMVF9GQVNUX0ZP",
            "UldBUkRfQ09NUExFVEVEEAISMwovRkFTVF9GT1JXQVJEX1BPTExJTkdfUkVT",
            "VUxUX0ZBU1RfRk9SV0FSRF9GQUlMRUQQA0KJAQoYaW8udGVtcG9yYWwuYXBp",
            "LmVudW1zLnYxQhFUaW1lU2tpcHBpbmdQcm90b1ABWiFnby50ZW1wb3JhbC5p",
            "by9hcGkvZW51bXMvdjE7ZW51bXOqAhdUZW1wb3JhbGlvLkFwaS5FbnVtcy5W",
            "MeoCGlRlbXBvcmFsaW86OkFwaTo6RW51bXM6OlYxYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Temporalio.Api.Enums.V1.FastForwardPollingResult), }, null, null));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// FastForwardPollingResult is the result of polling and waiting for a fast-forward to complete
  /// on a time-skipping execution.
  /// FAST_FORWARD_POLLING_RESULT_POLL_TIMEOUT and FAST_FORWARD_POLLING_RESULT_FAST_FORWARD_COMPLETED
  /// are the normal poll outcomes; FAST_FORWARD_POLLING_RESULT_FAST_FORWARD_FAILED means the
  /// fast-forward can no longer complete.
  /// </summary>
  public enum FastForwardPollingResult {
    /// <summary>
    /// Never returned; guards against an unset result.
    /// </summary>
    [pbr::OriginalName("FAST_FORWARD_POLLING_RESULT_UNSPECIFIED")] Unspecified = 0,
    /// <summary>
    /// The poll timed out server-side before the fast-forward completed. The caller may poll again.
    /// </summary>
    [pbr::OriginalName("FAST_FORWARD_POLLING_RESULT_POLL_TIMEOUT")] PollTimeout = 1,
    /// <summary>
    /// The fast-forward identified by the request's `fast_forward_id` reached its target time and completed.
    /// </summary>
    [pbr::OriginalName("FAST_FORWARD_POLLING_RESULT_FAST_FORWARD_COMPLETED")] FastForwardCompleted = 2,
    /// <summary>
    /// The fast-forward can no longer complete, which usually indicates improper usage of
    /// fast-forward on the client side. Possible reasons: the `fast_forward_id` does not match
    /// the execution's current fast-forward, the execution ended before the fast-forward
    /// completed, the fast-forward config was updated while the poll was in flight, etc.
    /// See `failed_reason` in the response for the specific cause.
    /// </summary>
    [pbr::OriginalName("FAST_FORWARD_POLLING_RESULT_FAST_FORWARD_FAILED")] FastForwardFailed = 3,
  }

  #endregion

}

#endregion Designer generated code
