namespace Temporalio.Tests.Nexus;

using System.Text;
using System.Text.Json;
using Temporalio.Nexus;
using Xunit;

public class NexusWorkflowRunHandleTests
{
    [Fact]
    public void ToToken_RoundTrips()
    {
        var handle = new NexusWorkflowRunHandle("my-namespace", "my-workflow-id", 0);
        var token = handle.ToToken();
        var decoded = NexusWorkflowRunHandle.FromToken(token);

        Assert.Equal("my-namespace", decoded.Namespace);
        Assert.Equal("my-workflow-id", decoded.WorkflowId);
        Assert.Equal(0, decoded.Version);
    }

    [Fact]
    public void ToToken_UsesBase64Url_NoPadding()
    {
        var handle = new NexusWorkflowRunHandle("my-namespace", "my-workflow-id", 0);
        var token = handle.ToToken();

        // Base64url should not contain + or / or =
        Assert.DoesNotContain("+", token);
        Assert.DoesNotContain("/", token);
        Assert.DoesNotContain("=", token);
    }

    [Fact]
    public void ToToken_JsonUsesCorrectKeys()
    {
        var handle = new NexusWorkflowRunHandle("ns", "wid", 0);
        var token = handle.ToToken();

        // Decode manually to inspect JSON
        var json = Encoding.UTF8.GetString(NexusWorkflowRunHandle.Base64UrlDecode(token));
        using var doc = JsonDocument.Parse(json);
        var root = doc.RootElement;

        // Key must be "t" (not "t'")
        Assert.Equal(1, root.GetProperty("t").GetInt32());
        Assert.Equal("ns", root.GetProperty("ns").GetString());
        Assert.Equal("wid", root.GetProperty("wid").GetString());
    }

    [Fact]
    public void FromToken_AcceptsVersionNull()
    {
        var json = """{"t":1,"ns":"ns","wid":"wid","v":null}""";
        var token = NexusWorkflowRunHandle.Base64UrlEncode(Encoding.UTF8.GetBytes(json));

        var handle = NexusWorkflowRunHandle.FromToken(token);

        Assert.Equal("ns", handle.Namespace);
        Assert.Equal("wid", handle.WorkflowId);
        Assert.Equal(0, handle.Version);
    }

    [Fact]
    public void FromToken_AcceptsVersionZero()
    {
        var json = """{"t":1,"ns":"ns","wid":"wid","v":0}""";
        var token = NexusWorkflowRunHandle.Base64UrlEncode(Encoding.UTF8.GetBytes(json));

        var handle = NexusWorkflowRunHandle.FromToken(token);

        Assert.Equal(0, handle.Version);
    }

    [Fact]
    public void FromToken_RejectsUnsupportedVersion()
    {
        var json = """{"t":1,"ns":"ns","wid":"wid","v":1}""";
        var token = NexusWorkflowRunHandle.Base64UrlEncode(Encoding.UTF8.GetBytes(json));

        Assert.Throws<ArgumentException>(() => NexusWorkflowRunHandle.FromToken(token));
    }

    [Fact]
    public void FromToken_RejectsInvalidBase64()
    {
        Assert.Throws<ArgumentException>(() => NexusWorkflowRunHandle.FromToken("!!!invalid!!!"));
    }

    [Fact]
    public void FromToken_RejectsInvalidJson()
    {
        var token = NexusWorkflowRunHandle.Base64UrlEncode(Encoding.UTF8.GetBytes("not valid json"));
        Assert.Throws<ArgumentException>(() => NexusWorkflowRunHandle.FromToken(token));
    }

    [Fact]
    public void CrossSdkCompatibility_PythonToken()
    {
        // This token was generated by Python SDK with {"t":1,"ns":"default","wid":"my-wf"} and base64url encoding
        var pythonToken = "eyJ0IjoxLCJucyI6ImRlZmF1bHQiLCJ3aWQiOiJteS13ZiJ9";

        var handle = NexusWorkflowRunHandle.FromToken(pythonToken);

        Assert.Equal("default", handle.Namespace);
        Assert.Equal("my-wf", handle.WorkflowId);
        Assert.Equal(0, handle.Version);
    }

    [Fact]
    public void ToToken_SpecialCharactersInValues_RoundTrips()
    {
        // Namespace/workflow IDs with characters that differ between base64 and base64url
        var handle = new NexusWorkflowRunHandle("ns/with+special", "wf?id=1&foo=bar", 0);
        var token = handle.ToToken();
        var decoded = NexusWorkflowRunHandle.FromToken(token);

        Assert.Equal("ns/with+special", decoded.Namespace);
        Assert.Equal("wf?id=1&foo=bar", decoded.WorkflowId);
    }
}
