namespace Temporalio.Tests.Nexus;

using System;
using System.Text;
using System.Text.Json;
using Temporalio.Nexus;
using Xunit;

public class NexusWorkflowRunHandleTests
{
    [Fact]
    public void ToToken_RoundTrips()
    {
        var handle = new NexusWorkflowRunHandle("my-namespace", "my-workflow-id", 0);
        var token = handle.ToToken();
        var decoded = NexusWorkflowRunHandle.FromToken(token);

        Assert.Equal("my-namespace", decoded.Namespace);
        Assert.Equal("my-workflow-id", decoded.WorkflowId);
        Assert.Equal(0, decoded.Version);
    }

    [Fact]
    public void ToToken_UsesBase64Url_NoPadding()
    {
        var handle = new NexusWorkflowRunHandle("my-namespace", "my-workflow-id", 0);
        var token = handle.ToToken();

        // Base64url should not contain + or / or =
        Assert.DoesNotContain("+", token);
        Assert.DoesNotContain("/", token);
        Assert.DoesNotContain("=", token);
    }

    [Fact]
    public void ToToken_JsonUsesCorrectKeys()
    {
        var handle = new NexusWorkflowRunHandle("ns", "wid", 0);
        var token = handle.ToToken();

        // Decode manually to inspect JSON
        var base64 = token.Replace('-', '+').Replace('_', '/');
        switch (base64.Length % 4)
        {
            case 2: base64 += "=="; break;
            case 3: base64 += "="; break;
        }
        var json = Encoding.UTF8.GetString(Convert.FromBase64String(base64));
        using var doc = JsonDocument.Parse(json);
        var root = doc.RootElement;

        // Key must be "t" (not "t'")
        Assert.Equal(1, root.GetProperty("t").GetInt32());
        Assert.Equal("ns", root.GetProperty("ns").GetString());
        Assert.Equal("wid", root.GetProperty("wid").GetString());
    }

    [Fact]
    public void FromToken_AcceptsVersionNull()
    {
        var json = """{"t":1,"ns":"ns","wid":"wid","v":null}""";
        var token = ToBase64Url(json);

        var handle = NexusWorkflowRunHandle.FromToken(token);

        Assert.Equal("ns", handle.Namespace);
        Assert.Equal("wid", handle.WorkflowId);
        Assert.Equal(0, handle.Version);
    }

    [Fact]
    public void FromToken_AcceptsVersionZero()
    {
        var json = """{"t":1,"ns":"ns","wid":"wid","v":0}""";
        var token = ToBase64Url(json);

        var handle = NexusWorkflowRunHandle.FromToken(token);

        Assert.Equal(0, handle.Version);
    }

    [Fact]
    public void FromToken_RejectsUnsupportedVersion()
    {
        var json = """{"t":1,"ns":"ns","wid":"wid","v":2}""";
        var token = ToBase64Url(json);

        Assert.Throws<ArgumentException>(() => NexusWorkflowRunHandle.FromToken(token));
    }

    [Fact]
    public void FromToken_RejectsInvalidBase64()
    {
        Assert.Throws<ArgumentException>(() => NexusWorkflowRunHandle.FromToken("!!!invalid!!!"));
    }

    [Fact]
    public void CrossSdkCompatibility_PythonToken()
    {
        // This token was generated by Python SDK with {"t":1,"ns":"default","wid":"my-wf"} and base64url encoding
        var pythonToken = "eyJ0IjoxLCJucyI6ImRlZmF1bHQiLCJ3aWQiOiJteS13ZiJ9";

        var handle = NexusWorkflowRunHandle.FromToken(pythonToken);

        Assert.Equal("default", handle.Namespace);
        Assert.Equal("my-wf", handle.WorkflowId);
    }

    [Fact]
    public void ToToken_SpecialCharactersInValues_RoundTrips()
    {
        // Namespace/workflow IDs with characters that differ between base64 and base64url
        var handle = new NexusWorkflowRunHandle("ns/with+special", "wf?id=1&foo=bar", 0);
        var token = handle.ToToken();
        var decoded = NexusWorkflowRunHandle.FromToken(token);

        Assert.Equal("ns/with+special", decoded.Namespace);
        Assert.Equal("wf?id=1&foo=bar", decoded.WorkflowId);
    }

    private static string ToBase64Url(string json) =>
        Convert.ToBase64String(Encoding.UTF8.GetBytes(json))
            .Replace('+', '-')
            .Replace('/', '_')
            .TrimEnd('=');
}
