// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: temporal/api/operatorservice/v1/service.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Temporalio.Api.OperatorService.V1 {

  /// <summary>Holder for reflection information generated from temporal/api/operatorservice/v1/service.proto</summary>
  public static partial class ServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for temporal/api/operatorservice/v1/service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ci10ZW1wb3JhbC9hcGkvb3BlcmF0b3JzZXJ2aWNlL3YxL3NlcnZpY2UucHJv",
            "dG8SH3RlbXBvcmFsLmFwaS5vcGVyYXRvcnNlcnZpY2UudjEaNnRlbXBvcmFs",
            "L2FwaS9vcGVyYXRvcnNlcnZpY2UvdjEvcmVxdWVzdF9yZXNwb25zZS5wcm90",
            "bxocZ29vZ2xlL2FwaS9hbm5vdGF0aW9ucy5wcm90bzLVCAoPT3BlcmF0b3JT",
            "ZXJ2aWNlEpIBChNBZGRTZWFyY2hBdHRyaWJ1dGVzEjsudGVtcG9yYWwuYXBp",
            "Lm9wZXJhdG9yc2VydmljZS52MS5BZGRTZWFyY2hBdHRyaWJ1dGVzUmVxdWVz",
            "dBo8LnRlbXBvcmFsLmFwaS5vcGVyYXRvcnNlcnZpY2UudjEuQWRkU2VhcmNo",
            "QXR0cmlidXRlc1Jlc3BvbnNlIgASmwEKFlJlbW92ZVNlYXJjaEF0dHJpYnV0",
            "ZXMSPi50ZW1wb3JhbC5hcGkub3BlcmF0b3JzZXJ2aWNlLnYxLlJlbW92ZVNl",
            "YXJjaEF0dHJpYnV0ZXNSZXF1ZXN0Gj8udGVtcG9yYWwuYXBpLm9wZXJhdG9y",
            "c2VydmljZS52MS5SZW1vdmVTZWFyY2hBdHRyaWJ1dGVzUmVzcG9uc2UiABLN",
            "AQoUTGlzdFNlYXJjaEF0dHJpYnV0ZXMSPC50ZW1wb3JhbC5hcGkub3BlcmF0",
            "b3JzZXJ2aWNlLnYxLkxpc3RTZWFyY2hBdHRyaWJ1dGVzUmVxdWVzdBo9LnRl",
            "bXBvcmFsLmFwaS5vcGVyYXRvcnNlcnZpY2UudjEuTGlzdFNlYXJjaEF0dHJp",
            "YnV0ZXNSZXNwb25zZSI4gtPkkwIyEjAvYXBpL3YxL25hbWVzcGFjZXMve25h",
            "bWVzcGFjZX0vc2VhcmNoLWF0dHJpYnV0ZXMShgEKD0RlbGV0ZU5hbWVzcGFj",
            "ZRI3LnRlbXBvcmFsLmFwaS5vcGVyYXRvcnNlcnZpY2UudjEuRGVsZXRlTmFt",
            "ZXNwYWNlUmVxdWVzdBo4LnRlbXBvcmFsLmFwaS5vcGVyYXRvcnNlcnZpY2Uu",
            "djEuRGVsZXRlTmFtZXNwYWNlUmVzcG9uc2UiABKhAQoYQWRkT3JVcGRhdGVS",
            "ZW1vdGVDbHVzdGVyEkAudGVtcG9yYWwuYXBpLm9wZXJhdG9yc2VydmljZS52",
            "MS5BZGRPclVwZGF0ZVJlbW90ZUNsdXN0ZXJSZXF1ZXN0GkEudGVtcG9yYWwu",
            "YXBpLm9wZXJhdG9yc2VydmljZS52MS5BZGRPclVwZGF0ZVJlbW90ZUNsdXN0",
            "ZXJSZXNwb25zZSIAEpIBChNSZW1vdmVSZW1vdGVDbHVzdGVyEjsudGVtcG9y",
            "YWwuYXBpLm9wZXJhdG9yc2VydmljZS52MS5SZW1vdmVSZW1vdGVDbHVzdGVy",
            "UmVxdWVzdBo8LnRlbXBvcmFsLmFwaS5vcGVyYXRvcnNlcnZpY2UudjEuUmVt",
            "b3ZlUmVtb3RlQ2x1c3RlclJlc3BvbnNlIgASfQoMTGlzdENsdXN0ZXJzEjQu",
            "dGVtcG9yYWwuYXBpLm9wZXJhdG9yc2VydmljZS52MS5MaXN0Q2x1c3RlcnNS",
            "ZXF1ZXN0GjUudGVtcG9yYWwuYXBpLm9wZXJhdG9yc2VydmljZS52MS5MaXN0",
            "Q2x1c3RlcnNSZXNwb25zZSIAQrYBCiJpby50ZW1wb3JhbC5hcGkub3BlcmF0",
            "b3JzZXJ2aWNlLnYxQgxTZXJ2aWNlUHJvdG9QAVo1Z28udGVtcG9yYWwuaW8v",
            "YXBpL29wZXJhdG9yc2VydmljZS92MTtvcGVyYXRvcnNlcnZpY2WqAiFUZW1w",
            "b3JhbGlvLkFwaS5PcGVyYXRvclNlcnZpY2UuVjHqAiRUZW1wb3JhbGlvOjpB",
            "cGk6Ok9wZXJhdG9yU2VydmljZTo6VjFiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Temporalio.Api.OperatorService.V1.RequestResponseReflection.Descriptor, global::Temporalio.Api.Dependencies.Google.Api.AnnotationsReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
