using System.Diagnostics;
using System.Text;
using System.Text.RegularExpressions;
using Google.Protobuf.Reflection;

var currFile = new StackTrace(true).GetFrame(0)?.GetFileName();
var projectDir = Path.GetFullPath(Path.Join(currFile, "../../../"));
var generatorDir = Path.Join(projectDir, "src/Temporalio.SystemNexus.Generator");
var protoDir = Path.Join(projectDir, "src/Temporalio/Bridge/sdk-core/crates/protos/protos");
var apiProtoDir = Path.Join(protoDir, "api_upstream");
var descriptorPath = Path.Join(generatorDir, "obj/SystemNexus/temporal_api.bin");
var outputDir = Path.Join(projectDir, "src/Temporalio/SystemNexus/Generated");
var operationsPath = Path.Join(outputDir, "Operations.cs");

EnsureNexGen();
BuildDescriptor();
GenerateNexusApi();
GeneratePayloadVisitorRegistry(operationsPath, descriptorPath);
return 0;

void EnsureNexGen()
{
    var nexGenCommand = NexGenCommand();
    if (RunProcess(nexGenCommand, new[] { "help" }, ignoreExitCode: true) == 0)
    {
        return;
    }

    if (Environment.GetEnvironmentVariable("NEX_GEN_BIN") is { Length: > 0 })
    {
        throw new InvalidOperationException($"Unable to run nex-gen command {nexGenCommand}");
    }

    RunProcess("cargo", new[] { "install", "--locked", "nex-gen", "--force" });
}

void BuildDescriptor()
{
    Directory.CreateDirectory(Path.GetDirectoryName(descriptorPath)!);
    RunProcess(
        "protoc",
        new[]
        {
            "-I=" + apiProtoDir,
            "-I=" + protoDir,
            "--include_imports",
            "--descriptor_set_out=" + descriptorPath,
            Path.Join(apiProtoDir, "temporal/api/workflowservice/v1/request_response.proto"),
        });
}

void GenerateNexusApi()
{
    if (Directory.Exists(outputDir))
    {
        new DirectoryInfo(outputDir).Delete(true);
    }

    Directory.CreateDirectory(outputDir);
    RunProcess(
        NexGenCommand(),
        new[]
        {
            "generate",
            "--lang",
            "dotnet",
            "--input",
            Path.Join(generatorDir, "wit/workflow-service.wit"),
            "--input",
            Path.Join(generatorDir, "wit/deps"),
            "--descriptors",
            descriptorPath,
            "--output",
            outputDir,
        });
}

static void GeneratePayloadVisitorRegistry(string operationsPath, string descriptorPath)
{
    var generatedDir = Path.GetDirectoryName(operationsPath) ??
        throw new InvalidOperationException($"No directory for {operationsPath}");
    var servicePath = Path.Combine(generatedDir, "Service.cs");
    var source = File.ReadAllText(servicePath);
    var namespaceMatch = Regex.Match(
        source,
        @"namespace\s+(?<namespace>[A-Za-z0-9_.]+)\s*\{",
        RegexOptions.Multiline);
    if (!namespaceMatch.Success)
    {
        throw new InvalidOperationException($"No generated namespace found in {servicePath}");
    }

    var generatedNamespace = namespaceMatch.Groups["namespace"].Value;
    var operations = ParseOperations(source);
    if (operations.Count == 0)
    {
        throw new InvalidOperationException($"No generated operations found in {servicePath}");
    }

    var messages = LoadMessages(descriptorPath);
    var messagesByCsharpType = messages.Values.ToDictionary(
        message => NormalizeTypeName(message.CsharpType),
        message => message);
    var operationMessages = operations.Select(operation =>
        new OperationMessages(
            operation,
            GetMessage(messagesByCsharpType, operation.InputType),
            GetMessage(messagesByCsharpType, operation.OutputType))).ToList();
    var containsPayloadMemo = new Dictionary<string, bool>();
    var emittedMethods = new HashSet<string>();
    var builder = new StringBuilder();

    builder.AppendLine("// <auto-generated />");
    builder.AppendLine("// Generated by Temporalio.SystemNexus.Generator. DO NOT EDIT!");
    builder.AppendLine("#nullable enable");
    builder.AppendLine();
    builder.AppendLine("using System;");
    builder.AppendLine("using System.Threading.Tasks;");
    builder.AppendLine("using Google.Protobuf;");
    builder.AppendLine("using Google.Protobuf.Collections;");
    builder.AppendLine("using Temporalio.Api.Common.V1;");
    builder.AppendLine("using Temporalio.Converters;");
    builder.AppendLine($"using {generatedNamespace};");
    builder.AppendLine();
    builder.AppendLine("namespace Temporalio.Worker");
    builder.AppendLine("{");
    builder.AppendLine("    internal static class SystemNexusPayloadVisitorRegistry");
    builder.AppendLine("    {");
    builder.AppendLine("        internal delegate Task PayloadVisitor(Payload payload);");
    builder.AppendLine("        internal delegate Task PayloadsVisitor(RepeatedField<Payload> payloads);");
    builder.AppendLine("        internal delegate Task EnvelopeVisitor(Payload payload);");
    builder.AppendLine();
    builder.AppendLine("        private static readonly BinaryProtoConverter ProtoPayloadConverter = new();");
    builder.AppendLine();
    builder.AppendLine("        internal static bool TryToInputPayload(");
    builder.AppendLine("            string service,");
    builder.AppendLine("            string operation,");
    builder.AppendLine("            object? value,");
    builder.AppendLine("            out Payload payload)");
    builder.AppendLine("        {");
    builder.AppendLine("            payload = null!;");
    builder.AppendLine("            if (!NexGenOperationRegistry.Operations.ContainsKey((service, operation)))");
    builder.AppendLine("            {");
    builder.AppendLine("                return false;");
    builder.AppendLine("            }");
    builder.AppendLine();

    foreach (var operation in operationMessages)
    {
        var serviceLiteral = CsharpLiteral(operation.Operation.Service);
        var operationLiteral = CsharpLiteral(operation.Operation.Operation);
        builder.AppendLine(
            $"            if (service == {serviceLiteral} && operation == {operationLiteral})");
        builder.AppendLine("            {");
        builder.AppendLine($"                if (value is not {operation.Input.CsharpType} typedValue)");
        builder.AppendLine("                {");
        builder.AppendLine("                    return false;");
        builder.AppendLine("                }");
        builder.AppendLine();
        builder.AppendLine("                ProtoPayloadConverter.TryToPayload(typedValue, out var converted);");
        builder.AppendLine("                payload = converted!;");
        builder.AppendLine("                return true;");
        builder.AppendLine("            }");
        builder.AppendLine();
    }

    builder.AppendLine("            return false;");
    builder.AppendLine("        }");
    builder.AppendLine();
    builder.AppendLine("        internal static Task<bool> TryVisitInputAsync(");
    builder.AppendLine("            string service,");
    builder.AppendLine("            string operation,");
    builder.AppendLine("            Payload payload,");
    builder.AppendLine("            PayloadVisitor visitPayload,");
    builder.AppendLine("            PayloadsVisitor visitPayloads,");
    builder.AppendLine("            EnvelopeVisitor? visitEnvelope = null) =>");
    builder.AppendLine("            TryVisitAsync(service, operation, input: true, payload, visitPayload, visitPayloads, visitEnvelope);");
    builder.AppendLine();
    builder.AppendLine("        internal static Task<bool> TryVisitOutputAsync(");
    builder.AppendLine("            string service,");
    builder.AppendLine("            string operation,");
    builder.AppendLine("            Payload payload,");
    builder.AppendLine("            PayloadVisitor visitPayload,");
    builder.AppendLine("            PayloadsVisitor visitPayloads,");
    builder.AppendLine("            EnvelopeVisitor? visitEnvelope = null) =>");
    builder.AppendLine("            TryVisitAsync(service, operation, input: false, payload, visitPayload, visitPayloads, visitEnvelope);");
    builder.AppendLine();
    builder.AppendLine("        private static async Task<bool> TryVisitAsync(");
    builder.AppendLine("            string service,");
    builder.AppendLine("            string operation,");
    builder.AppendLine("            bool input,");
    builder.AppendLine("            Payload payload,");
    builder.AppendLine("            PayloadVisitor visitPayload,");
    builder.AppendLine("            PayloadsVisitor visitPayloads,");
    builder.AppendLine("            EnvelopeVisitor? visitEnvelope)");
    builder.AppendLine("        {");
    builder.AppendLine("            if (!NexGenOperationRegistry.Operations.ContainsKey((service, operation)))");
    builder.AppendLine("            {");
    builder.AppendLine("                return false;");
    builder.AppendLine("            }");
    builder.AppendLine();

    foreach (var operation in operationMessages)
    {
        var serviceLiteral = CsharpLiteral(operation.Operation.Service);
        var operationLiteral = CsharpLiteral(operation.Operation.Operation);
        builder.AppendLine(
            $"            if (service == {serviceLiteral} && operation == {operationLiteral})");
        builder.AppendLine("            {");
        builder.AppendLine("                if (input)");
        builder.AppendLine("                {");
        builder.AppendLine(
            $"                    await VisitEnvelopeAsync<{operation.Input.CsharpType}>(payload, {VisitMethodName(operation.Input)}, visitPayload, visitPayloads, visitEnvelope).ConfigureAwait(false);");
        builder.AppendLine("                }");
        builder.AppendLine("                else");
        builder.AppendLine("                {");
        builder.AppendLine(
            $"                    await VisitEnvelopeAsync<{operation.Output.CsharpType}>(payload, {VisitMethodName(operation.Output)}, visitPayload, visitPayloads, visitEnvelope).ConfigureAwait(false);");
        builder.AppendLine("                }");
        builder.AppendLine();
        builder.AppendLine("                return true;");
        builder.AppendLine("            }");
        builder.AppendLine();
    }

    builder.AppendLine("            return false;");
    builder.AppendLine("        }");
    builder.AppendLine();
    builder.AppendLine("        private static async Task VisitEnvelopeAsync<T>(");
    builder.AppendLine("            Payload payload,");
    builder.AppendLine("            Func<T, PayloadVisitor, PayloadsVisitor, Task> visitMessage,");
    builder.AppendLine("            PayloadVisitor visitPayload,");
    builder.AppendLine("            PayloadsVisitor visitPayloads,");
    builder.AppendLine("            EnvelopeVisitor? visitEnvelope)");
    builder.AppendLine("            where T : IMessage<T>, new()");
    builder.AppendLine("        {");
    builder.AppendLine("            BinaryProtoConverter.AssertProtoPayload(payload, typeof(T));");
    builder.AppendLine("            var message = new T();");
    builder.AppendLine("            message.MergeFrom(payload.Data);");
    builder.AppendLine("            await visitMessage(message, visitPayload, visitPayloads).ConfigureAwait(false);");
    builder.AppendLine("            payload.Metadata.Clear();");
    builder.AppendLine("            payload.Metadata[\"encoding\"] = ByteString.CopyFromUtf8(\"binary/protobuf\");");
    builder.AppendLine("            payload.Metadata[\"messageType\"] = ByteString.CopyFromUtf8(message.Descriptor.FullName);");
    builder.AppendLine("            payload.Data = message.ToByteString();");
    builder.AppendLine("            if (visitEnvelope != null)");
    builder.AppendLine("            {");
    builder.AppendLine("                await visitEnvelope(payload).ConfigureAwait(false);");
    builder.AppendLine("            }");
    builder.AppendLine("        }");
    builder.AppendLine();

    foreach (var operation in operationMessages)
    {
        EmitVisitMethod(builder, operation.Input, messages, containsPayloadMemo, emittedMethods);
        EmitVisitMethod(builder, operation.Output, messages, containsPayloadMemo, emittedMethods);
    }

    builder.AppendLine("    }");
    builder.AppendLine("}");

    File.WriteAllText(Path.Combine(generatedDir, "SystemNexusPayloadVisitorRegistry.cs"), builder.ToString());
}

static List<OperationInfo> ParseOperations(string serviceSource)
{
    var operations = new List<OperationInfo>();
    var serviceMatches = Regex.Matches(
        serviceSource,
        @"\[NexusService\(""(?<service>[^""]+)""\)\]\s+internal\s+interface\s+\w+\s*\{(?<body>.*?)^\s*\}",
        RegexOptions.Multiline | RegexOptions.Singleline,
        TimeSpan.FromSeconds(5));
    foreach (Match serviceMatch in serviceMatches)
    {
        var service = serviceMatch.Groups["service"].Value;
        var operationMatches = Regex.Matches(
            serviceMatch.Groups["body"].Value,
            @"\[NexusOperation\(""(?<operation>[^""]+)""\)\]\s+(?<output>[A-Za-z0-9_.:]+)\s+\w+\((?<input>[A-Za-z0-9_.:]+)\s+\w+\);",
            RegexOptions.Multiline,
            TimeSpan.FromSeconds(5));
        foreach (Match operationMatch in operationMatches)
        {
            operations.Add(new OperationInfo(
                service,
                operationMatch.Groups["operation"].Value,
                NormalizeTypeName(operationMatch.Groups["input"].Value),
                NormalizeTypeName(operationMatch.Groups["output"].Value)));
        }
    }

    return operations;
}

static IReadOnlyDictionary<string, MessageInfo> LoadMessages(string descriptorPath)
{
    var descriptorSet = FileDescriptorSet.Parser.ParseFrom(File.ReadAllBytes(descriptorPath));
    var messages = new Dictionary<string, MessageInfo>();
    foreach (var file in descriptorSet.File)
    {
        var csharpNamespace = file.Options?.CsharpNamespace;
        if (string.IsNullOrEmpty(csharpNamespace))
        {
            continue;
        }

        foreach (var message in file.MessageType)
        {
            AddMessage(messages, file.Package, $"global::{csharpNamespace}", message);
        }
    }

    return messages;
}

static void AddMessage(
    Dictionary<string, MessageInfo> messages,
    string protoPrefix,
    string csharpPrefix,
    DescriptorProto descriptor)
{
    var fullName = string.IsNullOrEmpty(protoPrefix) ?
        descriptor.Name :
        $"{protoPrefix}.{descriptor.Name}";
    var csharpType = $"{csharpPrefix}.{descriptor.Name}";
    messages[fullName] = new MessageInfo(fullName, csharpType, descriptor);
    foreach (var nested in descriptor.NestedType)
    {
        AddMessage(messages, fullName, $"{csharpType}.Types", nested);
    }
}

static MessageInfo GetMessage(
    IReadOnlyDictionary<string, MessageInfo> messagesByCsharpType,
    string csharpType)
{
    if (!messagesByCsharpType.TryGetValue(NormalizeTypeName(csharpType), out var message))
    {
        throw new InvalidOperationException($"No protobuf message descriptor found for {csharpType}");
    }

    return message;
}

static void EmitVisitMethod(
    StringBuilder builder,
    MessageInfo message,
    IReadOnlyDictionary<string, MessageInfo> messages,
    Dictionary<string, bool> containsPayloadMemo,
    HashSet<string> emittedMethods)
{
    if (!emittedMethods.Add(message.FullName))
    {
        return;
    }

    foreach (var referenced in ReferencedMessagesWithPayloads(message, messages, containsPayloadMemo))
    {
        EmitVisitMethod(builder, referenced, messages, containsPayloadMemo, emittedMethods);
    }

    builder.AppendLine($"        private static async Task {VisitMethodName(message)}(");
    builder.AppendLine($"            {message.CsharpType} value,");
    builder.AppendLine("            PayloadVisitor visitPayload,");
    builder.AppendLine("            PayloadsVisitor visitPayloads)");
    builder.AppendLine("        {");
    foreach (var line in VisitFieldLines(message, messages, containsPayloadMemo))
    {
        builder.AppendLine($"            {line}");
    }

    builder.AppendLine("            await Task.CompletedTask.ConfigureAwait(false);");
    builder.AppendLine("        }");
    builder.AppendLine();
}

static IEnumerable<MessageInfo> ReferencedMessagesWithPayloads(
    MessageInfo message,
    IReadOnlyDictionary<string, MessageInfo> messages,
    Dictionary<string, bool> containsPayloadMemo)
{
    foreach (var field in message.Descriptor.Field)
    {
        foreach (var referenced in FieldReferencedMessagesWithPayloads(field, messages, containsPayloadMemo))
        {
            yield return referenced;
        }
    }
}

static IEnumerable<MessageInfo> FieldReferencedMessagesWithPayloads(
    FieldDescriptorProto field,
    IReadOnlyDictionary<string, MessageInfo> messages,
    Dictionary<string, bool> containsPayloadMemo)
{
    if (!TryGetMessage(field.TypeName, messages, out var fieldMessage) ||
        IsPayload(fieldMessage) ||
        IsSearchAttributes(fieldMessage))
    {
        yield break;
    }

    if (fieldMessage.Descriptor.Options?.MapEntry == true)
    {
        var valueField = fieldMessage.Descriptor.Field.FirstOrDefault(field => field.Number == 2);
        if (valueField != null &&
            TryGetMessage(valueField.TypeName, messages, out var valueMessage) &&
            !IsPayload(valueMessage) &&
            !IsSearchAttributes(valueMessage) &&
            ContainsPayload(valueMessage, messages, containsPayloadMemo))
        {
            yield return valueMessage;
        }

        yield break;
    }

    if (ContainsPayload(fieldMessage, messages, containsPayloadMemo))
    {
        yield return fieldMessage;
    }
}

static IEnumerable<string> VisitFieldLines(
    MessageInfo message,
    IReadOnlyDictionary<string, MessageInfo> messages,
    Dictionary<string, bool> containsPayloadMemo)
{
    foreach (var field in message.Descriptor.Field)
    {
        if (!TryGetMessage(field.TypeName, messages, out var fieldMessage) ||
            IsSearchAttributes(fieldMessage))
        {
            continue;
        }

        var propertyName = PropertyName(field.Name, message.Descriptor.Name);
        if (fieldMessage.Descriptor.Options?.MapEntry == true)
        {
            var valueField = fieldMessage.Descriptor.Field.FirstOrDefault(field => field.Number == 2);
            if (valueField == null ||
                !TryGetMessage(valueField.TypeName, messages, out var valueMessage) ||
                IsSearchAttributes(valueMessage) ||
                !ContainsPayload(valueMessage, messages, containsPayloadMemo))
            {
                continue;
            }

            var valueName = UniqueLocalName(message, field, "item");
            yield return $"foreach (var {valueName} in value.{propertyName}.Values)";
            yield return "{";
            if (IsPayload(valueMessage))
            {
                yield return $"    if ({valueName} != null)";
                yield return "    {";
                yield return $"        await visitPayload({valueName}).ConfigureAwait(false);";
                yield return "    }";
            }
            else
            {
                yield return $"    if ({valueName} != null)";
                yield return "    {";
                yield return $"        await {VisitMethodName(valueMessage)}({valueName}, visitPayload, visitPayloads).ConfigureAwait(false);";
                yield return "    }";
            }

            yield return "}";
            continue;
        }

        if (!ContainsPayload(fieldMessage, messages, containsPayloadMemo))
        {
            continue;
        }

        if (IsPayload(fieldMessage))
        {
            if (field.Label == FieldDescriptorProto.Types.Label.Repeated)
            {
                var valueName = UniqueLocalName(message, field, "payload");
                yield return $"foreach (var {valueName} in value.{propertyName})";
                yield return "{";
                yield return $"    await visitPayload({valueName}).ConfigureAwait(false);";
                yield return "}";
            }
            else
            {
                yield return $"if (value.{propertyName} != null)";
                yield return "{";
                yield return $"    await visitPayload(value.{propertyName}).ConfigureAwait(false);";
                yield return "}";
            }
        }
        else if (IsPayloads(fieldMessage))
        {
            if (field.Label == FieldDescriptorProto.Types.Label.Repeated)
            {
                var valueName = UniqueLocalName(message, field, "payloads");
                yield return $"foreach (var {valueName} in value.{propertyName})";
                yield return "{";
                yield return $"    await visitPayloads({valueName}.Payloads_).ConfigureAwait(false);";
                yield return "}";
            }
            else
            {
                yield return $"if (value.{propertyName} != null)";
                yield return "{";
                yield return $"    await visitPayloads(value.{propertyName}.Payloads_).ConfigureAwait(false);";
                yield return "}";
            }
        }
        else if (field.Label == FieldDescriptorProto.Types.Label.Repeated)
        {
            var valueName = UniqueLocalName(message, field, "item");
            yield return $"foreach (var {valueName} in value.{propertyName})";
            yield return "{";
            yield return $"    await {VisitMethodName(fieldMessage)}({valueName}, visitPayload, visitPayloads).ConfigureAwait(false);";
            yield return "}";
        }
        else
        {
            yield return $"if (value.{propertyName} != null)";
            yield return "{";
            yield return $"    await {VisitMethodName(fieldMessage)}(value.{propertyName}, visitPayload, visitPayloads).ConfigureAwait(false);";
            yield return "}";
        }
    }
}

static bool ContainsPayload(
    MessageInfo message,
    IReadOnlyDictionary<string, MessageInfo> messages,
    Dictionary<string, bool> memo) =>
    ContainsPayloadCore(message, messages, memo, new HashSet<string>());

static bool ContainsPayloadCore(
    MessageInfo message,
    IReadOnlyDictionary<string, MessageInfo> messages,
    Dictionary<string, bool> memo,
    HashSet<string> visiting)
{
    if (IsSearchAttributes(message))
    {
        return false;
    }

    if (IsPayload(message) || IsPayloads(message))
    {
        return true;
    }

    if (memo.TryGetValue(message.FullName, out var result))
    {
        return result;
    }

    if (!visiting.Add(message.FullName))
    {
        return false;
    }

    result = false;
    foreach (var field in message.Descriptor.Field)
    {
        if (!TryGetMessage(field.TypeName, messages, out var fieldMessage) ||
            IsSearchAttributes(fieldMessage))
        {
            continue;
        }

        if (fieldMessage.Descriptor.Options?.MapEntry == true)
        {
            var valueField = fieldMessage.Descriptor.Field.FirstOrDefault(field => field.Number == 2);
            if (valueField != null &&
                TryGetMessage(valueField.TypeName, messages, out var valueMessage) &&
                ContainsPayloadCore(valueMessage, messages, memo, visiting))
            {
                result = true;
                break;
            }
        }
        else if (ContainsPayloadCore(fieldMessage, messages, memo, visiting))
        {
            result = true;
            break;
        }
    }

    visiting.Remove(message.FullName);
    memo[message.FullName] = result;
    return result;
}

static bool TryGetMessage(
    string typeName,
    IReadOnlyDictionary<string, MessageInfo> messages,
    out MessageInfo message) =>
    messages.TryGetValue(typeName.TrimStart('.'), out message!);

static bool IsPayload(MessageInfo message) => message.FullName == "temporal.api.common.v1.Payload";

static bool IsPayloads(MessageInfo message) => message.FullName == "temporal.api.common.v1.Payloads";

static bool IsSearchAttributes(MessageInfo message) =>
    message.FullName == "temporal.api.common.v1.SearchAttributes";

static string VisitMethodName(MessageInfo message) =>
    "Visit_" + Regex.Replace(message.FullName, @"[^A-Za-z0-9_]", "_");

static string PropertyName(string protoName, string messageName)
{
    var builder = new StringBuilder();
    var capitalizeNext = true;
    foreach (var ch in protoName)
    {
        if (ch == '_')
        {
            capitalizeNext = true;
            continue;
        }

        builder.Append(capitalizeNext ? char.ToUpperInvariant(ch) : ch);
        capitalizeNext = false;
    }

    var propertyName = builder.ToString();
    return propertyName == messageName ? propertyName + "_" : propertyName;
}

static int RunProcess(string fileName, IEnumerable<string> arguments, bool ignoreExitCode = false)
{
    var process = new Process
    {
        StartInfo =
        {
            FileName = fileName,
            UseShellExecute = false,
        },
    };
    foreach (var argument in arguments)
    {
        process.StartInfo.ArgumentList.Add(argument);
    }

    Console.WriteLine("Running {0} {1}", fileName, string.Join(" ", arguments));
    process.Start();
    process.WaitForExit();
    if (!ignoreExitCode && process.ExitCode != 0)
    {
        throw new InvalidOperationException($"{fileName} failed with exit code {process.ExitCode}");
    }

    return process.ExitCode;
}

static string NexGenCommand() =>
    Environment.GetEnvironmentVariable("NEX_GEN_BIN") is { Length: > 0 } value ? value : "nex-gen";

static string UniqueLocalName(MessageInfo message, FieldDescriptorProto field, string prefix) =>
    $"{prefix}_{Regex.Replace(message.FullName, @"[^A-Za-z0-9_]", "_")}_{field.Number}";

static string NormalizeTypeName(string typeName) =>
    typeName.StartsWith("global::", StringComparison.Ordinal) ? typeName["global::".Length..] : typeName;

static string CsharpLiteral(string value) => "@\"" + value.Replace("\"", "\"\"", StringComparison.Ordinal) + "\"";

internal sealed record OperationInfo(string Service, string Operation, string InputType, string OutputType);

internal sealed record OperationMessages(OperationInfo Operation, MessageInfo Input, MessageInfo Output);

internal sealed record MessageInfo(string FullName, string CsharpType, DescriptorProto Descriptor);
