name: Changelog

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]

permissions:
  contents: read
  pull-requests: read

jobs:
  changelog-check:
    name: Changelog checkpoint
    uses: temporalio/.github/.github/workflows/changelog-fragments.yml@b87e4183c4b74b7f6d4a2a7f3e77150da55cf733
    with:
      sdk-rust-path: src/Temporalio/Bridge/sdk-core
