name: Build Package
on:
  push:
    branches:
      - main
      - "releases/*"
  workflow_dispatch: {}
permissions:
  contents: read

jobs:
  build-bridge-libraries:
    strategy:
      fail-fast: false
      matrix:
        os:
          [
            ubuntu-latest,
            ubuntu-arm,
            alpine-latest,
            alpine-arm,
            macos-intel,
            macos-arm,
            windows-latest,
            windows-arm,
          ]
        include:
          - os: ubuntu-latest
            out-file: libtemporalio_sdk_core_c_bridge.so
            out-prefix: linux-x64
            # We use the Python manylinux image for glibc compatibility
            container: quay.io/pypa/manylinux2014_x86_64
            protobuf-url: https://github.com/protocolbuffers/protobuf/releases/download/v22.3/protoc-22.3-linux-x86_64.zip
          - os: ubuntu-arm
            out-file: libtemporalio_sdk_core_c_bridge.so
            out-prefix: linux-arm64
            runsOn: ubuntu-24.04-arm64-2-core
            # We use the Python manylinux image for glibc compatibility
            container: quay.io/pypa/manylinux2014_aarch64
            protobuf-url: https://github.com/protocolbuffers/protobuf/releases/download/v22.3/protoc-22.3-linux-aarch_64.zip
          - os: alpine-latest
            out-file: libtemporalio_sdk_core_c_bridge.so
            out-prefix: linux-musl-x64
            # Need Alpine container since GH runner doesn't have one
            container: mcr.microsoft.com/dotnet/sdk:10.0-alpine
            protobuf-url: https://github.com/protocolbuffers/protobuf/releases/download/v22.3/protoc-22.3-linux-x86_64.zip
            runsOn: ubuntu-latest
          - os: alpine-arm
            out-file: libtemporalio_sdk_core_c_bridge.so
            out-prefix: linux-musl-arm64
            # Need Alpine container since GH runner doesn't have one
            container: mcr.microsoft.com/dotnet/sdk:10.0-alpine
            protobuf-url: https://github.com/protocolbuffers/protobuf/releases/download/v22.3/protoc-22.3-linux-aarch_64.zip
            runsOn: ubuntu-24.04-arm64-2-core
          - os: macos-intel
            out-file: libtemporalio_sdk_core_c_bridge.dylib
            out-prefix: osx-x64
            runsOn: macos-15-intel
          - os: macos-arm
            out-file: libtemporalio_sdk_core_c_bridge.dylib
            out-prefix: osx-arm64
            runsOn: macos-14
          - os: windows-latest
            out-file: temporalio_sdk_core_c_bridge.dll
            out-prefix: win-x64
          - os: windows-arm
            out-file: temporalio_sdk_core_c_bridge.dll
            out-prefix: win-arm64
            runsOn: windows-11-arm
    runs-on: ${{ matrix.runsOn || matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          submodules: recursive

      - name: Install Rust
        if: ${{ !matrix.container }}
        uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8 # stable
        with:
          toolchain: stable

      - name: Setup Rust cache
        if: ${{ !matrix.container }}
        # Fixed version due to https://github.com/Swatinem/rust-cache/issues/183#issuecomment-1893979126
        uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2
        with:
          workspaces: src/Temporalio/Bridge
          key: ${{ matrix.os }}

      - name: Install protoc
        if: ${{ !matrix.container }}
        uses: arduino/setup-protoc@c65c819552d16ad3c9b72d9dfd5ba5237b9c906b # v3
        with:
          version: "23.x"
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build (non-Docker)
        if: ${{ !matrix.container }}
        run: cargo build --manifest-path src/Temporalio/Bridge/sdk-core/crates/sdk-core-c-bridge/Cargo.toml --profile release-lto

      - name: Build (Docker non-Alpine)
        if: ${{ matrix.container && matrix.os != 'alpine-latest' && matrix.os != 'alpine-arm' }}
        run: |
          docker run --rm -v "$(pwd):/workspace" -w /workspace \
            ${{ matrix.container }} \
            sh -c ' \
                curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain stable -y \
             && . $HOME/.cargo/env \
             && curl -LO ${{ matrix.protobuf-url }} \
             && unzip protoc-*.zip -d /usr/local/protobuf \
             && export PATH="$PATH:/usr/local/protobuf/bin" \
             && cargo build --manifest-path src/Temporalio/Bridge/sdk-core/crates/sdk-core-c-bridge/Cargo.toml --profile release-lto \
            '

      - name: Build (Docker Alpine)
        if: ${{ matrix.container && (matrix.os == 'alpine-latest' || matrix.os == 'alpine-arm') }}
        run: |
          docker run --rm -v "$(pwd):/workspace" -w /workspace \
            ${{ matrix.container }} \
            sh -c ' \
                curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain stable -y \
             && . $HOME/.cargo/env \
             && apk add --no-cache build-base \
             && curl -LO ${{ matrix.protobuf-url }} \
             && unzip protoc-*.zip -d /usr/local/protobuf \
             && export PATH="$PATH:/usr/local/protobuf/bin" \
             && RUSTFLAGS="-C target-feature=-crt-static" cargo build --manifest-path src/Temporalio/Bridge/sdk-core/crates/sdk-core-c-bridge/Cargo.toml --profile release-lto \
            '

      - name: Upload bridge library
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7
        with:
          name: ${{ matrix.out-prefix }}-bridge
          path: src/Temporalio/Bridge/sdk-core/target/release-lto/${{ matrix.out-file }}
          if-no-files-found: error

  build-nuget-package:
    needs:
      - build-bridge-libraries
    runs-on: windows-latest
    env:
      RestoreLockedMode: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          submodules: recursive

      - name: Download bridge libraries
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          path: bridge-libraries

      - name: Setup .NET
        uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7 # v5
        with:
          dotnet-version: 10.x

      - name: Build package
        run: dotnet pack -c Release /p:BridgeLibraryRoot=${{ github.workspace }}/bridge-libraries

      - name: Upload NuGet artifact
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7
        with:
          name: nuget-package
          path: |
            src/Temporalio/bin/Release/*.nupkg
            src/Temporalio/bin/Release/*.snupkg
            src/Temporalio.Extensions.DiagnosticSource/bin/Release/*.nupkg
            src/Temporalio.Extensions.DiagnosticSource/bin/Release/*.snupkg
            src/Temporalio.Extensions.Hosting/bin/Release/*.nupkg
            src/Temporalio.Extensions.Hosting/bin/Release/*.snupkg
            src/Temporalio.Extensions.OpenTelemetry/bin/Release/*.nupkg
            src/Temporalio.Extensions.OpenTelemetry/bin/Release/*.snupkg

  run-smoke-test:
    needs:
      - build-nuget-package
    strategy:
      fail-fast: false
      matrix:
        os:
          [
            ubuntu-latest,
            ubuntu-arm,
            alpine-latest,
            alpine-arm,
            macos-intel,
            macos-arm,
            windows-latest,
            windows-arm,
          ]
        include:
          - os: ubuntu-arm
            runsOn: ubuntu-24.04-arm64-2-core
          - os: alpine-latest
            runsOn: ubuntu-latest
          - os: alpine-arm
            # Run in Docker manually to avoid JS action limitations on ARM64
            runsOn: ubuntu-24.04-arm64-2-core
          - os: macos-intel
            runsOn: macos-15-intel
          - os: macos-arm
            runsOn: macos-14
          - os: windows-arm
            runsOn: windows-11-arm
    runs-on: ${{ matrix.runsOn || matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          submodules: recursive

      - name: Download NuGet artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          name: nuget-package
          path: ${{ github.workspace }}/nuget-package

      - name: Setup .NET (non-Alpine)
        uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7 # v5
        if: ${{ !contains(matrix.os, 'alpine') }}
        with:
          # Specific .NET version required because GitHub macos ARM image has
          # bad pre-installed .NET version
          dotnet-version: 10.x

      - name: Run smoke test (Alpine)
        if: ${{ contains(matrix.os, 'alpine') }}
        # Use Docker specifically for Alpine ARM 64 to avoid JS action limitations
        run: |
          docker run --rm -v "$(pwd):/workspace" -w /workspace \
            mcr.microsoft.com/dotnet/sdk:10.0-alpine \
            sh -c ' \
                dotnet add tests/Temporalio.SmokeTest package Temporalio -s "/workspace/nuget-package/Temporalio/bin/Release;https://api.nuget.org/v3/index.json" --prerelease \
             && dotnet run --project tests/Temporalio.SmokeTest \
            '

      - name: Run smoke test (Linux/macOS)
        if: ${{ !contains(matrix.os, 'alpine') && !contains(matrix.os, 'windows') }}
        run: |
          dotnet add tests/Temporalio.SmokeTest package Temporalio -s "$GITHUB_WORKSPACE/nuget-package/Temporalio/bin/Release;https://api.nuget.org/v3/index.json" --prerelease
          dotnet run --project tests/Temporalio.SmokeTest

      - name: Run smoke test (Windows)
        if: ${{ contains(matrix.os, 'windows') }}
        run: |
          dotnet add tests/Temporalio.SmokeTest package Temporalio -s "$env:GITHUB_WORKSPACE/nuget-package/Temporalio/bin/Release;https://api.nuget.org/v3/index.json" --prerelease
          dotnet run --project tests/Temporalio.SmokeTest

      - name: Setup msbuild (Windows x64 only)
        if: ${{ matrix.os == 'windows-latest' }}
        uses: microsoft/setup-msbuild@30375c66a4eea26614e0d39710365f22f8b0af57 # v3

      - name: Run .NET framework smoke test (Windows x64 only)
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          dotnet add tests/Temporalio.SmokeTestDotNetFramework package Temporalio -s "$env:GITHUB_WORKSPACE/nuget-package/Temporalio/bin/Release;https://api.nuget.org/v3/index.json" --prerelease
          msbuild tests/Temporalio.SmokeTestDotNetFramework -t:restore,build -p:Platform=x64
          tests/Temporalio.SmokeTestDotNetFramework/bin/x64/Debug/Temporalio.SmokeTestDotNetFramework.exe
